/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ResultPanel: typeof import('./src/components/layout/ResultPanel.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    WorkflowCanvas: typeof import('./src/components/WorkflowCanvas.vue')['default']
    Workspace: typeof import('./src/components/layout/Workspace.vue')['default']
  }
}
